CREATE TABLE variants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    text LONGTEXT NOT NULL,
    onset_date VARCHAR(255) NOT NULL
);

-- INSERT INTO variants (name, text, onset_date) VALUES
-- ('Variant Nigérian', 'Initialement séquencé en août 2020 au Nigéria8, les implications pour la transmission et la virulence ne sont pas claires, mais il a été répertorié comme une variante émergente par les Centres pour le contrôle et la prévention des maladies des États-Unis.', 'aout 2020'),
-- ('Variant Britannique', "Détecté pour la première fois en octobre 2020 lors de la pandémie de Covid-19 au Royaume-Uni à partir d'un échantillon prélevé le mois précédent10, le variant VOC-202012/01 (first Variant Of Concern in December 2020), auparavant connu sous le nom « VUI – 202012/01 » (first Variant Under Investigation in December 2020)11 est également nommé « B.1.1.7 » (souche, ou lignée, B.1.1.7) ou « 20B/501Y.V1 ».", 'octobre 2020'),
-- ('Variant Danois', 'Début novembre 2020, le variant danois, également appelé ΔFVI-spike par le State Serum Institute (SSI)17, été découvert dans le Jutland du Nord, au Danemark, et aurait été propagé des visons aux humains via des fermes de visons.', 'novembre 2020'),
-- ('Variant Sud-Africain', 'deLe 18 décembre 2020, le variant appelé 501.V2, 20C/501Y.V2 ou lignée B.1.35113 est détecté pour la première fois en Afrique du Sud et signalé par le département de la santé du pays.', 'décembre 2020'),
-- ('Variant Brésilien', "Le variant B.1.1.248 du SARS-CoV-2 a été détecté à Tokyo le 6 janvier 2021 par l'Institut national des maladies infectieuses (NIID). Ce nouveau variant a été trouvé chez quatre personnes arrivées le 2 janvier 2021 à Tokyo depuis l'État d'Amazonas au Brésil.", 'janvier 2021'),
-- ('Variant P1', "Il s'agit d'un variant détecté en décembre 2020 dans la région de Manaus au Brésil. Il est responsable d'une seconde vague extrêmement intense dans l'État de l'Amazonas et plus particulièrement dans la ville de Manaus, alors même que la ville avait atteint le seuil d'immunité collective en octobre 2020 avec 76 % de la population déjà exposée au Covid-19.", 'décembre 2020'),
-- ('Variant 20A EU.1', "Le 30 octobre 2020, des scientifiques suisses, américains et espagnols publient l'étude d’un variant du SARS-CoV-2, appelé 20A EU.134. Ce variant semble avoir émergé parmi des travailleurs agricoles en Aragon, dans le nord-est de l’Espagne, « C’est du moins les traces les plus anciennes de sa présence que nous avons pu détecter », précise Emma Hodcroft, l’auteure principale de l’étude et spécialiste de la génétique évolutive humaine à l’université de Bâle, d'après France.", 'octobre 2020'),
-- ('Variant Californien', "Le variant CAL.20C ou B1.1.429 a été observé pour la première fois par des chercheurs du Cedars-Sinai Medical Center en juillet 2020 dans l'un des 1 230 échantillons de virus recueillis dans le comté de Los Angeles. Le variant a été détecté à nouveau dans le sud de la Californie en octobre 2020. En novembre 2020, le variant CAL.20C représentait 36 % des échantillons collectés au Cedars-Sinai Medical Center et, en janvier 2021, le variant CAL.20C représentait 50 % des échantillons.", 'juillet 2020'),
-- ('Variant New-Yorkais', "Le variant B.1.526 dit 'new-yorkais' a été observé pour la première fois en novembre 2020 sur l’île de Manhattan. En janvier 2021 3 % des contaminations à New York sont des cas du variant B.1.526, fin février 2021, une augmentation jusqu'à 27% des séquences virales au moins est observée40,41. Des cas à Westchester, dans le Bronx et le Queens, le sud de Manhattan et à Brooklyn sont détectés.", 'novembre 2020'),
-- ('Variant Breton', "Le variant 20C dit « breton » a été détecté en Bretagne avec plusieurs malades présentant les symptômes de la Covid-19 rattachés à un cluster au centre hospitalier de Lannion (Côtes d'Armor) mais avec des tests PCR négatifs.", 'mars 2021'),
-- ('Variant Philippin', "Le variant P3 dit ''philippin'' a été découvert dans la région des visayas centrales à la mi-mars 202146. C'est un variant dit de troisième génération, qui aurait muté à partir du variant B.1.1.248, qui est de seconde génération. B.1.1.248 a lui-même muté de P1, qui constitue la première génération de cette lignée. Il serait présent depuis au moins début février 2021.", 'mars 2021'),
-- ('Variant Henri-Mondor', "L'équipe du laboratoire de virologie de l'hôpital Henri-Mondor AP-HP et l'équipe de la plateforme « génomique » ont récemment découvert un nouveau variant appelé « variant Henri-Mondor », annonce l’Assistance Publique - Hôpitaux de Paris (AP-HP)48,49. Ce variant a été découvert à Créteil, dans un cluster de trois professionnels hospitaliers et du conjoint de l'un d'entre eux.", 'février 2021'),
-- ('Variant Indien', "Détecté le 5 octobre 2020 près de Nagpur en Inde, le variant B.1.617 présente 15 mutations dont deux dans le domaine de liaison de la protéine spiculaire.", 'octobre 2020');